id = "programs.dev"
description = "Migrated feature programs.dev"

[packages]
pacman = [
  "gcc",
  "make",
  "cmake",
  "pkgconf",
  "gdb",
  "strace",
  "ltrace",
  "yq",
  "watchexec",
  "entr",
  "postgresql-libs",
  "sqlite",
  "sqlitebrowser",
  "python",
  "python-pip",
  "python-virtualenv",
  "python-pipx",
  "python-setuptools",
  "python-wheel",
  "uv",
  "python-numpy",
  "python-pandas",
  "python-matplotlib",
  "python-scipy",
  "python-requests",
  "python-typer",
  "python-pydantic",
  "python-sqlalchemy",
  "python-alembic",
  "python-psycopg",
  "python-asyncpg",
  "python-httpx",
  "python-pytest",
  "ipython",
  "pyside6",
  "python-gobject",
  "tk",
  "opencv",
  "python-pillow",
  "nodejs",
  "npm",
  "pnpm",
  "yarn",
  "typescript",
  "eslint",
  "vscode-css-languageserver",
  "vscode-html-languageserver",
  "vscode-json-languageserver",
  "dotnet-sdk",
  "dotnet-runtime",
  "aspnet-runtime",
  "fontconfig",
  "libx11",
  "libice",
  "libsm",
  "libxrandr",
  "libxcursor",
  "libxi",
  "wayland",
]
aur = []
