# Managed by Decman
# Ported from NixOS Hyprland exec-once.

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = echo 'Xft.dpi: 125' | xrdb -merge
exec-once = gsettings set org.gnome.desktop.interface text-scaling-factor 1.25

exec-once = dunst
exec-once = nm-applet --indicator
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Same autostart apps as in your NixOS module.
# If a program is not installed, Hyprland will just log the failed exec.
exec-once = steam
exec-once = Telegram
exec-once = zen-beta
exec-once = spotify
