# Managed by Decman
# Ported from nixos/modules/home-manager/desktop/hyprland/default.nix

source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr-generated/workspaces.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/settings.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf
