# Managed by Decman
# Ported from NixOS Hyprland default.nix.

xwayland {
    force_zero_scaling = false
}

general {
    gaps_in = 2
    gaps_out = 2
    border_size = 1
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 0
    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = false
        xray = false
        special = false
        ignore_opacity = true
        new_optimizations = true
        popups = true
        input_methods = true
        size = 8
        passes = 2
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = false
}

dwindle {
    preserve_split = true
    smart_split = false
    smart_resizing = true
}

misc {
    vfr = true
    vrr = 1
    animate_manual_resizes = false
    animate_mouse_windowdragging = false
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    on_focus_under_fullscreen = 2
    allow_session_lock_restore = true
    middle_click_paste = false
    focus_on_activate = false
}
