hostname = "proxy-01"
username = "root"
home = "/root"
machine_type = "server"
platform = "ubuntu"

features = ["ubuntu.server-base", "ubuntu.ssh-hardening", "services.3x-ui"]

[ssh]
port = 22
permit_root_login = "no"
allow_users = ["admin"]
allow_tcp_forwarding = "yes"
