hostname = "proxy-01"
username = "user"
home = "/home/user"
machine_type = "server"
platform = "ubuntu"

features = [
  "ubuntu.server-base",
  "ubuntu.users",
  "ubuntu.ssh-hardening",
  "services.xray-core",
  "ubuntu.firewall",
  "ubuntu.healthcheck",
]

[server_user]
name = "user"

ssh_public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH8OqzrbBUQOTEw84XyUWRjMa21jEwm4pbqsemXD0oWX user@archlinux"

[ssh]
port = 22
permit_root_login = "no"
allow_users = ["user"]

allow_tcp_forwarding = "local"

[firewall]
ssh_port = 22

# Открытые наружу proxy-порты.
# Панель 3x-ui сюда НЕ добавляем.
proxy_ports = ["443/tcp"]

# Панель слушает 127.0.0.1, поэтому наружу порт 2053 не открывается.
panel_port = 2053

# Если когда-нибудь захочешь открыть панель только со своего IP:
# panel_allow_from = ["1.2.3.4"]
panel_allow_from = []

[xui]
panel_port = 2053

# auto = сгенерировать один раз и сохранить в /etc/archctl/3x-ui.generated.env
web_base_path = "auto"
username = "auto"
password = "auto"

# Важно: панель доступна только через SSH tunnel.
listen_ip = "127.0.0.1"

# true = прогонять официальный installer при каждом switch.
# Обычно лучше false.
force_update = "false"

[xray]
public_host = "5.181.202.37"

port = 443
listen = "0.0.0.0"

sni = "www.nvidia.com"
target = "www.nvidia.com:443"

uuid = "cdcabd9c-7292-4886-a1fc-767082745767"
private_key = "6Cjy4cOIuY2I5RPYgotlOfsRsKUvXW8iVICfiLaPCkk"
public_key = "SX6bGQjzOtpap-sUsjyiYFq_6UtK6Pf7JMOmfg1jBTE"
short_id = "7e124cb33c130836"
xhttp_path = "/f8e2f68b38287d4e"

xhttp_mode = "packet-up"
fingerprint = "chrome"
dns_strategy = "UseIPv4"
client_name = "Arch-XHTTP-Reality"

force_update = "false"
