id = "base.secrets"
description = "Migrated feature base.secrets"

[packages]
pacman = ["sops", "age"]
aur = []

[[dirs]]
target = "/etc/sops/age"
permissions = "755"

[[files]]
source = "templates/sops-age-readme.j2"
target = "/etc/sops/age/README"
mode = "template"
type = "file"
owner = "root"
group = "root"
permissions = "600"
