add_newline = true
scan_timeout = 100
command_timeout = 1500
follow_symlinks = false

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$rust\
$golang\
$cmd_duration\
$line_break\
$character"""

palette = "tokyonight"

[palettes.tokyonight]
background = "#090B17"
foreground = "#c0caf5"
blue = "#7aa2f7"
cyan = "#7dcfff"
green = "#9ece6a"
yellow = "#e0af68"
orange = "#ff9e64"
red = "#f7768e"
magenta = "#bb9af7"
comment = "#565f89"

[os]
disabled = false
style = "bold blue"

[os.symbols]
Arch = "󰣇 "
NixOS = "󱄅 "
Linux = "󰌽 "

[username]
show_always = false
style_user = "bold blue"
style_root = "bold red"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "bold cyan"
format = "[@$hostname]($style) "

[directory]
style = "bold cyan"
truncation_length = 4
truncate_to_repo = false
read_only = " 󰌾"
format = "[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = " "
style = "bold magenta"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold yellow"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "=${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = "\\$${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[python]
symbol = " "
style = "bold yellow"
format = "via [$symbol$version]($style) "
detect_extensions = ["py"]
detect_files = ["pyproject.toml", "requirements.txt", ".python-version"]
detect_folders = [".venv"]

[nodejs]
symbol = " "
style = "bold green"
format = "via [$symbol$version]($style) "
detect_extensions = ["js", "mjs", "cjs", "ts", "tsx"]
detect_files = ["package.json", ".node-version", ".nvmrc"]

[rust]
symbol = " "
style = "bold orange"
format = "via [$symbol$version]($style) "

[golang]
symbol = " "
style = "bold cyan"
format = "via [$symbol$version]($style) "

[cmd_duration]
min_time = 1500
style = "bold yellow"
format = "took [$duration]($style) "

[character]
success_symbol = "[➜](bold cyan)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[❮](bold blue)"
vimcmd_replace_one_symbol = "[❮](bold magenta)"
vimcmd_replace_symbol = "[❮](bold magenta)"
vimcmd_visual_symbol = "[❮](bold yellow)"
